project:
  type: website

website:
  title: UNICEF AI4D Poverty Mapping Project
  navbar:
    title: false
    background: primary

  sidebar:
    contents:
      - href: index.qmd
        text: Main
      - href: about.qmd
        text: About
      - href: progress.qmd
        text: Progress
      - section: "Sprint 1 (Individual DHS Countries)"
        contents:
          - href: notebooks/2023-01-17-initial-model-ph-mm-tl-kh/model_ph.ipynb
          - href: notebooks/2023-01-17-initial-model-ph-mm-tl-kh/model_kh.ipynb
          - href: notebooks/2023-01-17-initial-model-ph-mm-tl-kh/model_mm.ipynb
          - href: notebooks/2023-01-17-initial-model-ph-mm-tl-kh/model_tl.ipynb
      - section: "Sprint 2 (Cross Country Experiments)"
        contents:
          - href: cross-country-report.qmd 
          - href: notebooks/2023-01-24-dhs-cross-country-experiments/2023-02-06_crosscountry_normalized.ipynb
          - href: notebooks/2023-01-24-dhs-cross-country-experiments/2023-01-24_crosscountry_initial.ipynb
          - href: notebooks/2023-02-01-index-recalculation-experiments/2023-02-06_index_recalculation.ipynb


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



