single_country_models:
  - name: "timor-leste"
    country_code: "tl"
    country_osm: "east-timor"
    model_weights_url: "https://drive.google.com/tl"
    dhs_stata_prefix: "dhs/tl/TLHR71DT/TLHR71DT"
    dhs_geo_prefix: "dhs/tl/TLGE71FL/TLGE71FL"
    ookla_year: "2019"
    nightlights_year: "2020"

  - name: "philippines"
    country_code: "ph"
    country_osm: "philippines"
    model_weights_url: "https://drive.google.com/ph"
    dhs_stata_prefix: "dhs/ph/PHHR71DT/PHHR71DT"
    dhs_geo_prefix: "dhs/ph/PHGE71FL/PHGE71FL"
    ookla_year: "2019"
    nightlights_year: "2020"

  - name: "cambodia"
    country_code: "kh"
    country_osm: "cambodia"
    model_weights_url: "https://drive.google.com/kh"
    dhs_stata_prefix: "dhs/kh/KHHR73DT/KHHR73DT"
    dhs_geo_prefix: "dhs/kh/KHGE71FL/KHGE71FL"
    ookla_year: "2019"
    nightlights_year: "2020"

  - name: "myanmar"
    country_code: "mm"
    country_osm: "myanmar"
    model_weights_url: "https://drive.google.com/mm"
    dhs_stata_prefix: "dhs/mm/MMHR71DT/MMHR71DT"
    dhs_geo_prefix: "dhs/mm/MMGE71FL/MMGE71FL"
    ookla_year: "2019"
    nightlights_year: "2020"

cross_country_model:
  model_weights_url: "https://drive.google.com/cross"

